# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqHnp_vaEg17-j7NCjvvS9K64h8e4bL2
"""

print("Hello world")

a="嘿嘿"
b="好好"
print(a+b)

a=input()
b="你好"
print(a+b)

C=12
N=30
print(C+N)

num3 =input()
num4 =input()
print(num3+num4)